name: Cloud Task Orchestrator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

permissions:
  actions: write
  contents: read

jobs:
  run-website:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        job: [1, 2, 3, 4, 5]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run script
        timeout-minutes: 340
        run: node main.js
